-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (win64) Build 6140274 Thu May 22 00:12:29 MDT 2025
-- Date        : Tue Jul 15 21:28:47 2025
-- Host        : DESKTOP-JP2R5GF running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ sys_top_nvme_ctrl_0_0_stub.vhdl
-- Design      : sys_top_nvme_ctrl_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu17eg-ffvc1760-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s0_axi_aclk : in STD_LOGIC;
    s0_axi_aresetn : in STD_LOGIC;
    s0_axi_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s0_axi_awready : out STD_LOGIC;
    s0_axi_awvalid : in STD_LOGIC;
    s0_axi_awprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s0_axi_wvalid : in STD_LOGIC;
    s0_axi_wready : out STD_LOGIC;
    s0_axi_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s0_axi_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s0_axi_bvalid : out STD_LOGIC;
    s0_axi_bready : in STD_LOGIC;
    s0_axi_bresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s0_axi_arvalid : in STD_LOGIC;
    s0_axi_arready : out STD_LOGIC;
    s0_axi_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s0_axi_arprot : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s0_axi_rvalid : out STD_LOGIC;
    s0_axi_rready : in STD_LOGIC;
    s0_axi_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s0_axi_rresp : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m0_axi_aclk : in STD_LOGIC;
    m0_axi_aresetn : in STD_LOGIC;
    m0_axi_awid : out STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m0_axi_awlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m0_axi_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m0_axi_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m0_axi_awlock : out STD_LOGIC;
    m0_axi_awcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m0_axi_awprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m0_axi_awregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m0_axi_awqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m0_axi_awuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_awvalid : out STD_LOGIC;
    m0_axi_awready : in STD_LOGIC;
    m0_axi_wid : out STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_wdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m0_axi_wstrb : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m0_axi_wlast : out STD_LOGIC;
    m0_axi_wuser : out STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_wvalid : out STD_LOGIC;
    m0_axi_wready : in STD_LOGIC;
    m0_axi_bid : in STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_bresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m0_axi_bvalid : in STD_LOGIC;
    m0_axi_buser : in STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_bready : out STD_LOGIC;
    m0_axi_arid : out STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m0_axi_arlen : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m0_axi_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m0_axi_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m0_axi_arlock : out STD_LOGIC;
    m0_axi_arcache : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m0_axi_arprot : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m0_axi_arregion : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m0_axi_arqos : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m0_axi_aruser : out STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_arvalid : out STD_LOGIC;
    m0_axi_arready : in STD_LOGIC;
    m0_axi_rid : in STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_rdata : in STD_LOGIC_VECTOR ( 63 downto 0 );
    m0_axi_rresp : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m0_axi_rlast : in STD_LOGIC;
    m0_axi_ruser : in STD_LOGIC_VECTOR ( 0 to 0 );
    m0_axi_rvalid : in STD_LOGIC;
    m0_axi_rready : out STD_LOGIC;
    dev_irq_assert : out STD_LOGIC;
    pcie_ref_clk_p : in STD_LOGIC;
    pcie_ref_clk_n : in STD_LOGIC;
    pcie_perst_n : in STD_LOGIC;
    pci_exp_txp : out STD_LOGIC_VECTOR ( 15 downto 0 );
    pci_exp_txn : out STD_LOGIC_VECTOR ( 15 downto 0 );
    pci_exp_rxp : in STD_LOGIC_VECTOR ( 15 downto 0 );
    pci_exp_rxn : in STD_LOGIC_VECTOR ( 15 downto 0 );
    user_lnk_up : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "sys_top_nvme_ctrl_0_0,s_axi_nvme,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "package_project";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s0_axi_aclk,s0_axi_aresetn,s0_axi_awaddr[31:0],s0_axi_awready,s0_axi_awvalid,s0_axi_awprot[2:0],s0_axi_wvalid,s0_axi_wready,s0_axi_wdata[31:0],s0_axi_wstrb[3:0],s0_axi_bvalid,s0_axi_bready,s0_axi_bresp[1:0],s0_axi_arvalid,s0_axi_arready,s0_axi_araddr[31:0],s0_axi_arprot[2:0],s0_axi_rvalid,s0_axi_rready,s0_axi_rdata[31:0],s0_axi_rresp[1:0],m0_axi_aclk,m0_axi_aresetn,m0_axi_awid[0:0],m0_axi_awaddr[31:0],m0_axi_awlen[7:0],m0_axi_awsize[2:0],m0_axi_awburst[1:0],m0_axi_awlock,m0_axi_awcache[3:0],m0_axi_awprot[2:0],m0_axi_awregion[3:0],m0_axi_awqos[3:0],m0_axi_awuser[0:0],m0_axi_awvalid,m0_axi_awready,m0_axi_wid[0:0],m0_axi_wdata[63:0],m0_axi_wstrb[7:0],m0_axi_wlast,m0_axi_wuser[0:0],m0_axi_wvalid,m0_axi_wready,m0_axi_bid[0:0],m0_axi_bresp[1:0],m0_axi_bvalid,m0_axi_buser[0:0],m0_axi_bready,m0_axi_arid[0:0],m0_axi_araddr[31:0],m0_axi_arlen[7:0],m0_axi_arsize[2:0],m0_axi_arburst[1:0],m0_axi_arlock,m0_axi_arcache[3:0],m0_axi_arprot[2:0],m0_axi_arregion[3:0],m0_axi_arqos[3:0],m0_axi_aruser[0:0],m0_axi_arvalid,m0_axi_arready,m0_axi_rid[0:0],m0_axi_rdata[63:0],m0_axi_rresp[1:0],m0_axi_rlast,m0_axi_ruser[0:0],m0_axi_rvalid,m0_axi_rready,dev_irq_assert,pcie_ref_clk_p,pcie_ref_clk_n,pcie_perst_n,pci_exp_txp[15:0],pci_exp_txn[15:0],pci_exp_rxp[15:0],pci_exp_rxn[15:0],user_lnk_up";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s0_axi_aclk : signal is "xilinx.com:signal:clock:1.0 s0_axi_aclk CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s0_axi_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s0_axi_aclk : signal is "XIL_INTERFACENAME s0_axi_aclk, ASSOCIATED_BUSIF s0_axi, ASSOCIATED_RESET s0_axi_aresetn, FREQ_HZ 199998001, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN sys_top_zynq_ultra_ps_e_0_0_pl_clk2, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s0_axi_aresetn : signal is "xilinx.com:signal:reset:1.0 s0_axi_aresetn RST";
  attribute X_INTERFACE_MODE of s0_axi_aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s0_axi_aresetn : signal is "XIL_INTERFACENAME s0_axi_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s0_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 s0_axi AWADDR";
  attribute X_INTERFACE_MODE of s0_axi_awaddr : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s0_axi_awaddr : signal is "XIL_INTERFACENAME s0_axi, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 199998001, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN sys_top_zynq_ultra_ps_e_0_0_pl_clk2, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s0_axi_awready : signal is "xilinx.com:interface:aximm:1.0 s0_axi AWREADY";
  attribute X_INTERFACE_INFO of s0_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 s0_axi AWVALID";
  attribute X_INTERFACE_INFO of s0_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 s0_axi AWPROT";
  attribute X_INTERFACE_INFO of s0_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 s0_axi WVALID";
  attribute X_INTERFACE_INFO of s0_axi_wready : signal is "xilinx.com:interface:aximm:1.0 s0_axi WREADY";
  attribute X_INTERFACE_INFO of s0_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 s0_axi WDATA";
  attribute X_INTERFACE_INFO of s0_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 s0_axi WSTRB";
  attribute X_INTERFACE_INFO of s0_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 s0_axi BVALID";
  attribute X_INTERFACE_INFO of s0_axi_bready : signal is "xilinx.com:interface:aximm:1.0 s0_axi BREADY";
  attribute X_INTERFACE_INFO of s0_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 s0_axi BRESP";
  attribute X_INTERFACE_INFO of s0_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 s0_axi ARVALID";
  attribute X_INTERFACE_INFO of s0_axi_arready : signal is "xilinx.com:interface:aximm:1.0 s0_axi ARREADY";
  attribute X_INTERFACE_INFO of s0_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 s0_axi ARADDR";
  attribute X_INTERFACE_INFO of s0_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 s0_axi ARPROT";
  attribute X_INTERFACE_INFO of s0_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 s0_axi RVALID";
  attribute X_INTERFACE_INFO of s0_axi_rready : signal is "xilinx.com:interface:aximm:1.0 s0_axi RREADY";
  attribute X_INTERFACE_INFO of s0_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 s0_axi RDATA";
  attribute X_INTERFACE_INFO of s0_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 s0_axi RRESP";
  attribute X_INTERFACE_INFO of m0_axi_aclk : signal is "xilinx.com:signal:clock:1.0 m0_axi_aclk CLK";
  attribute X_INTERFACE_MODE of m0_axi_aclk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m0_axi_aclk : signal is "XIL_INTERFACENAME m0_axi_aclk, ASSOCIATED_BUSIF m0_axi, ASSOCIATED_RESET m0_axi_aresetn, FREQ_HZ 249997498, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN sys_top_zynq_ultra_ps_e_0_0_pl_clk3, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m0_axi_aresetn : signal is "xilinx.com:signal:reset:1.0 m0_axi_aresetn RST";
  attribute X_INTERFACE_MODE of m0_axi_aresetn : signal is "slave";
  attribute X_INTERFACE_PARAMETER of m0_axi_aresetn : signal is "XIL_INTERFACENAME m0_axi_aresetn, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m0_axi_awid : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWID";
  attribute X_INTERFACE_MODE of m0_axi_awid : signal is "master";
  attribute X_INTERFACE_PARAMETER of m0_axi_awid : signal is "XIL_INTERFACENAME m0_axi, DATA_WIDTH 64, PROTOCOL AXI4, FREQ_HZ 249997498, ID_WIDTH 1, ADDR_WIDTH 32, AWUSER_WIDTH 1, ARUSER_WIDTH 1, WUSER_WIDTH 1, RUSER_WIDTH 1, BUSER_WIDTH 1, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN sys_top_zynq_ultra_ps_e_0_0_pl_clk3, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m0_axi_awaddr : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWADDR";
  attribute X_INTERFACE_INFO of m0_axi_awlen : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWLEN";
  attribute X_INTERFACE_INFO of m0_axi_awsize : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWSIZE";
  attribute X_INTERFACE_INFO of m0_axi_awburst : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWBURST";
  attribute X_INTERFACE_INFO of m0_axi_awlock : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWLOCK";
  attribute X_INTERFACE_INFO of m0_axi_awcache : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWCACHE";
  attribute X_INTERFACE_INFO of m0_axi_awprot : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWPROT";
  attribute X_INTERFACE_INFO of m0_axi_awregion : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWREGION";
  attribute X_INTERFACE_INFO of m0_axi_awqos : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWQOS";
  attribute X_INTERFACE_INFO of m0_axi_awuser : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWUSER";
  attribute X_INTERFACE_INFO of m0_axi_awvalid : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWVALID";
  attribute X_INTERFACE_INFO of m0_axi_awready : signal is "xilinx.com:interface:aximm:1.0 m0_axi AWREADY";
  attribute X_INTERFACE_INFO of m0_axi_wid : signal is "xilinx.com:interface:aximm:1.0 m0_axi WID";
  attribute X_INTERFACE_INFO of m0_axi_wdata : signal is "xilinx.com:interface:aximm:1.0 m0_axi WDATA";
  attribute X_INTERFACE_INFO of m0_axi_wstrb : signal is "xilinx.com:interface:aximm:1.0 m0_axi WSTRB";
  attribute X_INTERFACE_INFO of m0_axi_wlast : signal is "xilinx.com:interface:aximm:1.0 m0_axi WLAST";
  attribute X_INTERFACE_INFO of m0_axi_wuser : signal is "xilinx.com:interface:aximm:1.0 m0_axi WUSER";
  attribute X_INTERFACE_INFO of m0_axi_wvalid : signal is "xilinx.com:interface:aximm:1.0 m0_axi WVALID";
  attribute X_INTERFACE_INFO of m0_axi_wready : signal is "xilinx.com:interface:aximm:1.0 m0_axi WREADY";
  attribute X_INTERFACE_INFO of m0_axi_bid : signal is "xilinx.com:interface:aximm:1.0 m0_axi BID";
  attribute X_INTERFACE_INFO of m0_axi_bresp : signal is "xilinx.com:interface:aximm:1.0 m0_axi BRESP";
  attribute X_INTERFACE_INFO of m0_axi_bvalid : signal is "xilinx.com:interface:aximm:1.0 m0_axi BVALID";
  attribute X_INTERFACE_INFO of m0_axi_buser : signal is "xilinx.com:interface:aximm:1.0 m0_axi BUSER";
  attribute X_INTERFACE_INFO of m0_axi_bready : signal is "xilinx.com:interface:aximm:1.0 m0_axi BREADY";
  attribute X_INTERFACE_INFO of m0_axi_arid : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARID";
  attribute X_INTERFACE_INFO of m0_axi_araddr : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARADDR";
  attribute X_INTERFACE_INFO of m0_axi_arlen : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARLEN";
  attribute X_INTERFACE_INFO of m0_axi_arsize : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARSIZE";
  attribute X_INTERFACE_INFO of m0_axi_arburst : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARBURST";
  attribute X_INTERFACE_INFO of m0_axi_arlock : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARLOCK";
  attribute X_INTERFACE_INFO of m0_axi_arcache : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARCACHE";
  attribute X_INTERFACE_INFO of m0_axi_arprot : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARPROT";
  attribute X_INTERFACE_INFO of m0_axi_arregion : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARREGION";
  attribute X_INTERFACE_INFO of m0_axi_arqos : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARQOS";
  attribute X_INTERFACE_INFO of m0_axi_aruser : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARUSER";
  attribute X_INTERFACE_INFO of m0_axi_arvalid : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARVALID";
  attribute X_INTERFACE_INFO of m0_axi_arready : signal is "xilinx.com:interface:aximm:1.0 m0_axi ARREADY";
  attribute X_INTERFACE_INFO of m0_axi_rid : signal is "xilinx.com:interface:aximm:1.0 m0_axi RID";
  attribute X_INTERFACE_INFO of m0_axi_rdata : signal is "xilinx.com:interface:aximm:1.0 m0_axi RDATA";
  attribute X_INTERFACE_INFO of m0_axi_rresp : signal is "xilinx.com:interface:aximm:1.0 m0_axi RRESP";
  attribute X_INTERFACE_INFO of m0_axi_rlast : signal is "xilinx.com:interface:aximm:1.0 m0_axi RLAST";
  attribute X_INTERFACE_INFO of m0_axi_ruser : signal is "xilinx.com:interface:aximm:1.0 m0_axi RUSER";
  attribute X_INTERFACE_INFO of m0_axi_rvalid : signal is "xilinx.com:interface:aximm:1.0 m0_axi RVALID";
  attribute X_INTERFACE_INFO of m0_axi_rready : signal is "xilinx.com:interface:aximm:1.0 m0_axi RREADY";
  attribute X_INTERFACE_INFO of pcie_ref_clk_p : signal is "xilinx.com:signal:clock:1.0 pcie_ref_clk_p CLK, xilinx.com:interface:diff_clock:1.0 pcie_ref CLK_P";
  attribute X_INTERFACE_MODE of pcie_ref_clk_p : signal is "slave pcie_ref";
  attribute X_INTERFACE_PARAMETER of pcie_ref_clk_p : signal is "XIL_INTERFACENAME pcie_ref, CAN_DEBUG false, FREQ_HZ 100000000";
  attribute X_INTERFACE_INFO of pcie_ref_clk_n : signal is "xilinx.com:signal:clock:1.0 pcie_ref_clk_n CLK, xilinx.com:interface:diff_clock:1.0 pcie_ref CLK_N";
  attribute X_INTERFACE_MODE of pcie_ref_clk_n : signal is "slave pcie_ref_clk_n";
  attribute X_INTERFACE_PARAMETER of pcie_ref_clk_n : signal is "XIL_INTERFACENAME pcie_ref_clk_n, ASSOCIATED_RESET pcie_perst_n, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of pcie_perst_n : signal is "xilinx.com:signal:reset:1.0 pcie_perst_n RST";
  attribute X_INTERFACE_MODE of pcie_perst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of pcie_perst_n : signal is "XIL_INTERFACENAME pcie_perst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of pci_exp_txp : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pci_exp txp";
  attribute X_INTERFACE_MODE of pci_exp_txp : signal is "master";
  attribute X_INTERFACE_INFO of pci_exp_txn : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pci_exp txn";
  attribute X_INTERFACE_INFO of pci_exp_rxp : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pci_exp rxp";
  attribute X_INTERFACE_INFO of pci_exp_rxn : signal is "xilinx.com:interface:pcie_7x_mgt:1.0 pci_exp rxn";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "s_axi_nvme,Vivado 2025.1";
begin
end;
