# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'sys_top_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.srcs/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'sys_top_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_top_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
