#ifndef FILTER_TYPES_ABI_H_
#define FILTER_TYPES_ABI_H_

#define FILTER_VALUE_TYPE_INT32   1U
#define FILTER_VALUE_TYPE_INT64   2U
#define FILTER_VALUE_TYPE_FLOAT64 3U
#define FILTER_VALUE_TYPE_BYTES   4U

#endif /* FILTER_TYPES_ABI_H_ */
