# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sys_top/sys_top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top || ORIG_REF_NAME==sys_top} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==sys_top_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_axi_bram_ctrl_0_0_1/sys_top_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_axi_bram_ctrl_0_0 || ORIG_REF_NAME==sys_top_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_axi_bram_ctrl_1_0_1/sys_top_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_axi_bram_ctrl_1_0 || ORIG_REF_NAME==sys_top_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_axi_bram_ctrl_2_0_1/sys_top_axi_bram_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_axi_bram_ctrl_2_0 || ORIG_REF_NAME==sys_top_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_axi_bram_ctrl_3_0_1/sys_top_axi_bram_ctrl_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_axi_bram_ctrl_3_0 || ORIG_REF_NAME==sys_top_axi_bram_ctrl_3_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_bch_sccs_256B_21B_13b_0_0_1/sys_top_bch_sccs_256B_21B_13b_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_bch_sccs_256B_21B_13b_0_0 || ORIG_REF_NAME==sys_top_bch_sccs_256B_21B_13b_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_bch_sccs_256B_21B_13b_1_0_1/sys_top_bch_sccs_256B_21B_13b_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_bch_sccs_256B_21B_13b_1_0 || ORIG_REF_NAME==sys_top_bch_sccs_256B_21B_13b_1_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_bch_sccs_256B_21B_13b_2_0_1/sys_top_bch_sccs_256B_21B_13b_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_bch_sccs_256B_21B_13b_2_0 || ORIG_REF_NAME==sys_top_bch_sccs_256B_21B_13b_2_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_bch_sccs_256B_21B_13b_3_0_1/sys_top_bch_sccs_256B_21B_13b_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_bch_sccs_256B_21B_13b_3_0 || ORIG_REF_NAME==sys_top_bch_sccs_256B_21B_13b_3_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_blk_mem_gen_0_0_1/sys_top_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_blk_mem_gen_0_0 || ORIG_REF_NAME==sys_top_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_blk_mem_gen_1_0_1/sys_top_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_blk_mem_gen_1_0 || ORIG_REF_NAME==sys_top_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_blk_mem_gen_2_0_1/sys_top_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_blk_mem_gen_2_0 || ORIG_REF_NAME==sys_top_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_blk_mem_gen_3_0_1/sys_top_blk_mem_gen_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_blk_mem_gen_3_0 || ORIG_REF_NAME==sys_top_blk_mem_gen_3_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_0/sys_top_gpic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_0 || ORIG_REF_NAME==sys_top_gpic_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_upgraded_ipi_imp_xbar_0/sys_top_gpic_0_sub_0_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_0/sys_top_gpic_0_sub_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_1_upgraded_ipi_imp_xbar_0/sys_top_gpic_1_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_1_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==sys_top_gpic_1_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_1_0/sys_top_gpic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_1_0 || ORIG_REF_NAME==sys_top_gpic_1_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_upgraded_ipi_imp_xbar_0/sys_top_gpic_0_sub_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_1_1/sys_top_gpic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_1_1 || ORIG_REF_NAME==sys_top_gpic_1_1} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_upgraded_ipi_imp_xbar_0/sys_top_hpic_0_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==sys_top_hpic_0_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_0/sys_top_hpic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_0 || ORIG_REF_NAME==sys_top_hpic_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_pll_bank11_0_1/sys_top_pll_bank11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_pll_bank11_0 || ORIG_REF_NAME==sys_top_pll_bank11_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_pll_bank12_0_1/sys_top_pll_bank12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_pll_bank12_0 || ORIG_REF_NAME==sys_top_pll_bank12_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_pll_bank13_0 || ORIG_REF_NAME==sys_top_pll_bank13_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_0_0_1/sys_top_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_0_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_2_0/sys_top_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_2_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_t4nfc_hlper_0_0_1/sys_top_t4nfc_hlper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_t4nfc_hlper_0_0 || ORIG_REF_NAME==sys_top_t4nfc_hlper_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_t4nfc_hlper_1_0_1/sys_top_t4nfc_hlper_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_t4nfc_hlper_1_0 || ORIG_REF_NAME==sys_top_t4nfc_hlper_1_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_t4nfc_hlper_2_0_1/sys_top_t4nfc_hlper_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_t4nfc_hlper_2_0 || ORIG_REF_NAME==sys_top_t4nfc_hlper_2_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_t4nfc_hlper_3_0_1/sys_top_t4nfc_hlper_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_t4nfc_hlper_3_0 || ORIG_REF_NAME==sys_top_t4nfc_hlper_3_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_bch_skes_256B_21B_13b_0_0_1/sys_top_bch_skes_256B_21B_13b_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_bch_skes_256B_21B_13b_0_0 || ORIG_REF_NAME==sys_top_bch_skes_256B_21B_13b_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_iodelay_if_0_0/sys_top_iodelay_if_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_iodelay_if_0_0 || ORIG_REF_NAME==sys_top_iodelay_if_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_iodelay_if_0_2/sys_top_iodelay_if_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_iodelay_if_0_2 || ORIG_REF_NAME==sys_top_iodelay_if_0_2} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_1_0/sys_top_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_1_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_3_0/sys_top_proc_sys_reset_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_3_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_3_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_4_0/sys_top_proc_sys_reset_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_4_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_4_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_clk_wiz_0_0/sys_top_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_clk_wiz_0_0 || ORIG_REF_NAME==sys_top_clk_wiz_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_5_0/sys_top_proc_sys_reset_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_5_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_5_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_xlconcat_0_0/sys_top_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_xlconcat_0_0 || ORIG_REF_NAME==sys_top_xlconcat_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_smartconnect_0_0/sys_top_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_smartconnect_0_0 || ORIG_REF_NAME==sys_top_smartconnect_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_6_0/sys_top_proc_sys_reset_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_6_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_6_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_proc_sys_reset_7_0/sys_top_proc_sys_reset_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_proc_sys_reset_7_0 || ORIG_REF_NAME==sys_top_proc_sys_reset_7_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_nvme_ctrl_0_0/sys_top_nvme_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_nvme_ctrl_0_0 || ORIG_REF_NAME==sys_top_nvme_ctrl_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_v2nfc_0_0/sys_top_v2nfc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_v2nfc_0_0 || ORIG_REF_NAME==sys_top_v2nfc_0_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_v2nfc_0_1/sys_top_v2nfc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_v2nfc_0_1 || ORIG_REF_NAME==sys_top_v2nfc_0_1} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_v2nfc_0_2/sys_top_v2nfc_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_v2nfc_0_2 || ORIG_REF_NAME==sys_top_v2nfc_0_2} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_v2nfc_2_0/sys_top_v2nfc_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_v2nfc_2_0 || ORIG_REF_NAME==sys_top_v2nfc_2_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_imp_s00_data_fifo_0/sys_top_gpic_0_imp_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_imp_s00_data_fifo_0 || ORIG_REF_NAME==sys_top_gpic_0_imp_s00_data_fifo_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_imp_auto_cc_0/sys_top_gpic_0_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_imp_auto_cc_0 || ORIG_REF_NAME==sys_top_gpic_0_imp_auto_cc_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_s00_data_fifo_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_s00_data_fifo_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_0/sys_top_gpic_0_sub_0_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_0/sys_top_gpic_0_sub_0_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_0/sys_top_gpic_0_sub_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_1/sys_top_gpic_0_sub_0_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_1 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_1} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_1/sys_top_gpic_0_sub_0_imp_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_1 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_1} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_2/sys_top_gpic_0_sub_0_imp_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_2 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_2} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_2/sys_top_gpic_0_sub_0_imp_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_2 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_2} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_1/sys_top_gpic_0_sub_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_1 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_3/sys_top_gpic_0_sub_0_imp_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_3 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_3} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_3/sys_top_gpic_0_sub_0_imp_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_3 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_3} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_4/sys_top_gpic_0_sub_0_imp_auto_cc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_4 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_4} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_4/sys_top_gpic_0_sub_0_imp_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_4 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_4} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_2/sys_top_gpic_0_sub_0_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_2 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_2} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_5/sys_top_gpic_0_sub_0_imp_auto_cc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_5 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_5} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_5/sys_top_gpic_0_sub_0_imp_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_5 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_5} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_6/sys_top_gpic_0_sub_0_imp_auto_cc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_6 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_6} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_6/sys_top_gpic_0_sub_0_imp_auto_ds_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_6 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_6} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_3/sys_top_gpic_0_sub_0_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_3 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_pc_3} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_7/sys_top_gpic_0_sub_0_imp_auto_cc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_7 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_cc_7} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_7/sys_top_gpic_0_sub_0_imp_auto_ds_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_7 || ORIG_REF_NAME==sys_top_gpic_0_sub_0_imp_auto_ds_7} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_1_imp_s00_data_fifo_0/sys_top_gpic_1_imp_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_1_imp_s00_data_fifo_0 || ORIG_REF_NAME==sys_top_gpic_1_imp_s00_data_fifo_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_1_imp_auto_ds_0/sys_top_gpic_1_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_1_imp_auto_ds_0 || ORIG_REF_NAME==sys_top_gpic_1_imp_auto_ds_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_1_imp_auto_pc_0/sys_top_gpic_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_1_imp_auto_pc_0 || ORIG_REF_NAME==sys_top_gpic_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_1_imp_auto_cc_0/sys_top_gpic_1_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_1_imp_auto_cc_0 || ORIG_REF_NAME==sys_top_gpic_1_imp_auto_cc_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_imp_s00_data_fifo_0/sys_top_gpic_0_sub_imp_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_imp_s00_data_fifo_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_imp_s00_data_fifo_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_0/sys_top_gpic_0_sub_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_imp_auto_cc_0 || ORIG_REF_NAME==sys_top_gpic_0_sub_imp_auto_cc_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_1/sys_top_gpic_0_sub_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_gpic_0_sub_imp_auto_cc_1 || ORIG_REF_NAME==sys_top_gpic_0_sub_imp_auto_cc_1} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_s00_regslice_0/sys_top_hpic_0_imp_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_s00_regslice_0 || ORIG_REF_NAME==sys_top_hpic_0_imp_s00_regslice_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_0/sys_top_hpic_0_imp_auto_us_cc_df_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_0 || ORIG_REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_s01_regslice_0/sys_top_hpic_0_imp_s01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_s01_regslice_0 || ORIG_REF_NAME==sys_top_hpic_0_imp_s01_regslice_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_1/sys_top_hpic_0_imp_auto_us_cc_df_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_1 || ORIG_REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_1} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_s02_regslice_0/sys_top_hpic_0_imp_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_s02_regslice_0 || ORIG_REF_NAME==sys_top_hpic_0_imp_s02_regslice_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_2/sys_top_hpic_0_imp_auto_us_cc_df_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_2 || ORIG_REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_2} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_s03_regslice_0/sys_top_hpic_0_imp_s03_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_s03_regslice_0 || ORIG_REF_NAME==sys_top_hpic_0_imp_s03_regslice_0} -quiet] -quiet

# IP: bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_3/sys_top_hpic_0_imp_auto_us_cc_df_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_3 || ORIG_REF_NAME==sys_top_hpic_0_imp_auto_us_cc_df_3} -quiet] -quiet

# XDC: d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/sys_top_ooc.xdc
