# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.runs/synth_1/sys_top_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param bd.open.in_stealth_mode 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu17eg-ffvc1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.cache/wt [current_project]
set_property parent.project_path D:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.ipdefs/ip-repo_0_0 [current_project]
update_ip_catalog
set_property ip_output_repo d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib D:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/hdl/sys_top_wrapper.v
add_files D:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.srcs/sources_1/bd/sys_top/sys_top.bd
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_zynq_ultra_ps_e_0_0/sys_top_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_axi_bram_ctrl_0_0_1/sys_top_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_axi_bram_ctrl_1_0_1/sys_top_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_axi_bram_ctrl_2_0_1/sys_top_axi_bram_ctrl_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_axi_bram_ctrl_3_0_1/sys_top_axi_bram_ctrl_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_0_0_1/sys_top_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_1_0_1/sys_top_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_2_0_1/sys_top_blk_mem_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_blk_mem_gen_3_0_1/sys_top_blk_mem_gen_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_upgraded_ipi_imp_xbar_0/sys_top_gpic_0_sub_0_upgraded_ipi_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_upgraded_ipi_imp_xbar_0/sys_top_gpic_1_upgraded_ipi_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_upgraded_ipi_imp_xbar_0/sys_top_gpic_0_sub_upgraded_ipi_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_upgraded_ipi_imp_xbar_0/sys_top_hpic_0_upgraded_ipi_imp_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank11_0_1/sys_top_pll_bank11_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank11_0_1/sys_top_pll_bank11_0.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank11_0_1/sys_top_pll_bank11_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank12_0_1/sys_top_pll_bank12_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank12_0_1/sys_top_pll_bank12_0.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank12_0_1/sys_top_pll_bank12_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_pll_bank13_0_1/sys_top_pll_bank13_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_0_0_1/sys_top_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_0_0_1/sys_top_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_2_0/sys_top_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_2_0/sys_top_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_1_0/sys_top_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_1_0/sys_top_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_3_0/sys_top_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_3_0/sys_top_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_4_0/sys_top_proc_sys_reset_4_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_4_0/sys_top_proc_sys_reset_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_clk_wiz_0_0/sys_top_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_clk_wiz_0_0/sys_top_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_clk_wiz_0_0/sys_top_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_5_0/sys_top_proc_sys_reset_5_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_5_0/sys_top_proc_sys_reset_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_1/bd_fa2a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_5/bd_fa2a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_6/bd_fa2a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_7/bd_fa2a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_8/bd_fa2a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_9/bd_fa2a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_10/bd_fa2a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/bd_0/ip/ip_11/bd_fa2a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_smartconnect_0_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_6_0/sys_top_proc_sys_reset_6_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_6_0/sys_top_proc_sys_reset_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_7_0/sys_top_proc_sys_reset_7_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_proc_sys_reset_7_0/sys_top_proc_sys_reset_7_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/ip_0/synth/pcie4_uscale_plus_0_gt.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/synth/pcie4_uscale_plus_0_late.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_nvme_ctrl_0_0/src/pcie4_uscale_plus_0/source/ip_pcie4_uscale_plus_x1y0.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_1/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_1/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_0_2/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_v2nfc_2_0/src/IN_FIFO_ALT_16x512/IN_FIFO_ALT_16x512_clocks.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_imp_s00_data_fifo_0/sys_top_gpic_0_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_imp_s00_data_fifo_0/sys_top_gpic_0_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_imp_s00_data_fifo_0/sys_top_gpic_0_imp_s00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_imp_auto_cc_0/sys_top_gpic_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_imp_auto_cc_0/sys_top_gpic_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_imp_auto_cc_0/sys_top_gpic_0_imp_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0/sys_top_gpic_0_sub_0_imp_s00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_0/sys_top_gpic_0_sub_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_0/sys_top_gpic_0_sub_0_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_0/sys_top_gpic_0_sub_0_imp_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_0/sys_top_gpic_0_sub_0_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_0/sys_top_gpic_0_sub_0_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_0/sys_top_gpic_0_sub_0_imp_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_0/sys_top_gpic_0_sub_0_imp_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_1/sys_top_gpic_0_sub_0_imp_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_1/sys_top_gpic_0_sub_0_imp_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_1/sys_top_gpic_0_sub_0_imp_auto_cc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_1/sys_top_gpic_0_sub_0_imp_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_1/sys_top_gpic_0_sub_0_imp_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_1/sys_top_gpic_0_sub_0_imp_auto_ds_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_2/sys_top_gpic_0_sub_0_imp_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_2/sys_top_gpic_0_sub_0_imp_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_2/sys_top_gpic_0_sub_0_imp_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_2/sys_top_gpic_0_sub_0_imp_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_2/sys_top_gpic_0_sub_0_imp_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_2/sys_top_gpic_0_sub_0_imp_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_1/sys_top_gpic_0_sub_0_imp_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_3/sys_top_gpic_0_sub_0_imp_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_3/sys_top_gpic_0_sub_0_imp_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_3/sys_top_gpic_0_sub_0_imp_auto_cc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_3/sys_top_gpic_0_sub_0_imp_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_3/sys_top_gpic_0_sub_0_imp_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_3/sys_top_gpic_0_sub_0_imp_auto_ds_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_4/sys_top_gpic_0_sub_0_imp_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_4/sys_top_gpic_0_sub_0_imp_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_4/sys_top_gpic_0_sub_0_imp_auto_cc_4_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_4/sys_top_gpic_0_sub_0_imp_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_4/sys_top_gpic_0_sub_0_imp_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_4/sys_top_gpic_0_sub_0_imp_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_2/sys_top_gpic_0_sub_0_imp_auto_pc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_5/sys_top_gpic_0_sub_0_imp_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_5/sys_top_gpic_0_sub_0_imp_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_5/sys_top_gpic_0_sub_0_imp_auto_cc_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_5/sys_top_gpic_0_sub_0_imp_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_5/sys_top_gpic_0_sub_0_imp_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_5/sys_top_gpic_0_sub_0_imp_auto_ds_5_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_6/sys_top_gpic_0_sub_0_imp_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_6/sys_top_gpic_0_sub_0_imp_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_6/sys_top_gpic_0_sub_0_imp_auto_cc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_6/sys_top_gpic_0_sub_0_imp_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_6/sys_top_gpic_0_sub_0_imp_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_6/sys_top_gpic_0_sub_0_imp_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_pc_3/sys_top_gpic_0_sub_0_imp_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_7/sys_top_gpic_0_sub_0_imp_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_7/sys_top_gpic_0_sub_0_imp_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_cc_7/sys_top_gpic_0_sub_0_imp_auto_cc_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_7/sys_top_gpic_0_sub_0_imp_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_7/sys_top_gpic_0_sub_0_imp_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_0_imp_auto_ds_7/sys_top_gpic_0_sub_0_imp_auto_ds_7_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_s00_data_fifo_0/sys_top_gpic_1_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_s00_data_fifo_0/sys_top_gpic_1_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_s00_data_fifo_0/sys_top_gpic_1_imp_s00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_auto_ds_0/sys_top_gpic_1_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_auto_ds_0/sys_top_gpic_1_imp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_auto_ds_0/sys_top_gpic_1_imp_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_auto_pc_0/sys_top_gpic_1_imp_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_auto_cc_0/sys_top_gpic_1_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_auto_cc_0/sys_top_gpic_1_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_1_imp_auto_cc_0/sys_top_gpic_1_imp_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_s00_data_fifo_0/sys_top_gpic_0_sub_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_s00_data_fifo_0/sys_top_gpic_0_sub_imp_s00_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_s00_data_fifo_0/sys_top_gpic_0_sub_imp_s00_data_fifo_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_0/sys_top_gpic_0_sub_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_0/sys_top_gpic_0_sub_imp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_0/sys_top_gpic_0_sub_imp_auto_cc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_1/sys_top_gpic_0_sub_imp_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_1/sys_top_gpic_0_sub_imp_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_gpic_0_sub_imp_auto_cc_1/sys_top_gpic_0_sub_imp_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s00_regslice_0/sys_top_hpic_0_imp_s00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s00_regslice_0/sys_top_hpic_0_imp_s00_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_0/sys_top_hpic_0_imp_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_0/sys_top_hpic_0_imp_auto_us_cc_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_0/sys_top_hpic_0_imp_auto_us_cc_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s01_regslice_0/sys_top_hpic_0_imp_s01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s01_regslice_0/sys_top_hpic_0_imp_s01_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_1/sys_top_hpic_0_imp_auto_us_cc_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_1/sys_top_hpic_0_imp_auto_us_cc_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_1/sys_top_hpic_0_imp_auto_us_cc_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s02_regslice_0/sys_top_hpic_0_imp_s02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s02_regslice_0/sys_top_hpic_0_imp_s02_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_2/sys_top_hpic_0_imp_auto_us_cc_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_2/sys_top_hpic_0_imp_auto_us_cc_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_2/sys_top_hpic_0_imp_auto_us_cc_df_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s03_regslice_0/sys_top_hpic_0_imp_s03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_s03_regslice_0/sys_top_hpic_0_imp_s03_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_3/sys_top_hpic_0_imp_auto_us_cc_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_3/sys_top_hpic_0_imp_auto_us_cc_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/ip/sys_top_hpic_0_imp_auto_us_cc_df_3/sys_top_hpic_0_imp_auto_us_cc_df_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/tmp/daisyplus_lpddr4_b_25.1_250819/cosm-plus-sys.gen/sources_1/bd/sys_top/sys_top_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top sys_top_wrapper -part xczu17eg-ffvc1760-2-e -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sys_top_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file sys_top_wrapper_utilization_synth.rpt -pb sys_top_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
