#define _POSIX_C_SOURCE 200809L

#ifndef __PG_CUSTOM_PATHLIST_HOOK_H__
#define __PG_CUSTOM_PATHLIST_HOOK_H__

#include "pg_filter_common.h"
#include "share_mem.h"

// typedef struct PGCustomScanState_s {
//         CustomScanState		css;
// 	RelOptInfo              *baserel;
// 	HeapTupleData   	c_tuple;
// 	tupdesc_t		tupdesc;
// 	filter_t 		filter;
//         qual_t 			qual;
// 	int			max_attr_index;
// 	int			filter_cnt;
// 	char			filepath[128];
// 	int			blk_cnt;
// 	int			file_cnt;
//         share_mem_data_t 	*share_mem;
//         mem_blk_t       	*mem_blk;
// 	int 			conn;
// 	int			request_cnt;
// 	int			respond_cnt;
// 	int			blk_tuple_cnt;	
// 	int			total_tuple_cnt;	
// 	int			blk_index;
// 	int			tup_index;
// } PGCustomScanState;

typedef struct PGCustomScanState_s {
        CustomScanState		css;
	RelOptInfo              *baserel;
	HeapTupleData   	c_tuple;
	tupdesc_t		tupdesc;
	filter_t 		filter;
        qual_t 			qual;
	int			max_attr_index;
	int			filter_cnt;
	char			filepath[128];
	int			blk_cnt;
	int			file_cnt;
    char 	*share_mem;
    mem_blk_t       	*mem_blk;
	int 			conn;
	int			result_page_cnt;             //结果集页面个数
	int			cur_page_tuple_cnt;			//当前页面元组总数
	int			total_tuple_cnt;	
	int 		cur_result_page_index;     //当前页面索引
	int			cur_result_tup_index;     //当前元组索引
	int flag;//0 获取结果集状态 1 处理结果集状态  3结束
	int filter_extents_cnt;// 根据文件划分的过滤请求个数
    extent_info_t filter_extents[100000]; // 每个过滤请求对应的 extent 信息
	int cur_filter_extents_index;//当前需要处理的filter_extents 索引
	page_t pages[16];// 接收一次数据的缓冲区
	double nvme_total_time;
} PGCustomScanState;

/*FpgaCustomScan Copy from PostgreSQL Kernel add rel in CustomScan*/
typedef struct FpgaCustomScan
{
        Scan            scan;
        uint32          flags;                  /* mask of CUSTOMPATH_* flags, see
                                                                 * nodes/extensible.h */
        List       *custom_plans;       /* list of Plan nodes, if any */
        List       *custom_exprs;       /* expressions that custom code may evaluate */
        List       *custom_private; /* private data for custom code */
        List       *custom_scan_tlist;  /* optional tlist describing scan tuple */
        Bitmapset  *custom_relids;      /* RTIs generated by this scan */
        const struct CustomScanMethods *methods;

	//Add for CustomScan
	RelOptInfo* rel;
} FpgaCustomScan;

void PGSetCustomRelPathlistHook (PlannerInfo* root,
                               RelOptInfo* rel,
                               Index rti,
                               RangeTblEntry* rte);
void test_page(TupleTableSlot *slot);
#endif
