#ifndef FILTER_CONFIG_H_
#define FILTER_CONFIG_H_

/* Validated high-throughput firmware profile. Every value remains overridable
 * through the existing CMake compile definitions. */
#ifndef FILTER_ACCEL_ENABLE
#define FILTER_ACCEL_ENABLE 1
#endif

/* Fixed by the current firmware/RTL descriptor-table ABI. */
#define FILTER_ACCEL_MAX_BATCH_PAGES 64U
#define FILTER_ACCEL_MAX_TUPLES_PER_PAGE 128

#ifndef DATA_BUFFER_ENTRIES_PER_DIE
#define DATA_BUFFER_ENTRIES_PER_DIE 128
#endif

#ifndef REQUEST_ENTRIES_PER_DIE
#define REQUEST_ENTRIES_PER_DIE 512
#endif

#ifndef FILTER_MAX_BLOCK_COUNT
#define FILTER_MAX_BLOCK_COUNT 8192U
#endif

#ifndef FILTER_RESULT_MAX_PAGES
#define FILTER_RESULT_MAX_PAGES 32
#endif

#ifndef FILTER_PROJECTION_ENABLE
#define FILTER_PROJECTION_ENABLE 1
#endif

#ifndef FILTER_COMPUTE_ENABLE
#define FILTER_COMPUTE_ENABLE 1
#endif

#ifndef FILTER_HASH_JOIN_ENABLE
#define FILTER_HASH_JOIN_ENABLE 1
#endif

#ifndef FILTER_COMPUTE_MAX_SORT_ROWS
#define FILTER_COMPUTE_MAX_SORT_ROWS 4096U
#endif

#ifndef FILTER_COMPUTE_MAX_TUPLE_BYTES
#define FILTER_COMPUTE_MAX_TUPLE_BYTES 8192U
#endif

#ifndef FILTER_COMPUTE_WORK_BYTES
#define FILTER_COMPUTE_WORK_BYTES 0x02200000U
#endif

#ifndef FILTER_JOIN_MIN_BUCKETS
#define FILTER_JOIN_MIN_BUCKETS 64U
#endif

#ifndef FILTER_JOIN_MAX_BUCKETS
#define FILTER_JOIN_MAX_BUCKETS 262144U
#endif

#ifndef FILTER_JOIN_MAX_BUILD_ROWS
#define FILTER_JOIN_MAX_BUILD_ROWS 1048576U
#endif

#ifndef FILTER_JOIN_MAX_OUTPUT_ROWS
#define FILTER_JOIN_MAX_OUTPUT_ROWS 1048576U
#endif

#ifndef FILTER_JOIN_WORK_BYTES
#define FILTER_JOIN_WORK_BYTES 0x08000000U
#endif

/* One independent FPGA output slot is reserved for every page in a batch.
 * Keeping a full PostgreSQL page per slot gives the hardware a hard bound and
 * makes batch fallback independent between pages. */
#ifndef FILTER_PROJECTION_STAGING_BYTES_PER_PAGE
#define FILTER_PROJECTION_STAGING_BYTES_PER_PAGE 8192U
#endif

#ifndef FILTER_PROJECTION_DEFAULT_MAX_ROW_BYTES
#define FILTER_PROJECTION_DEFAULT_MAX_ROW_BYTES 4096U
#endif

#ifndef FILTER_ACCEL_VERIFY_ENABLE
#define FILTER_ACCEL_VERIFY_ENABLE 0
#endif

#ifndef FILTER_FORCE_ARM_FALLBACK
#define FILTER_FORCE_ARM_FALLBACK 0
#endif

#ifndef FILTER_STAGING_BATCH_ENABLE
#define FILTER_STAGING_BATCH_ENABLE 0
#endif

#ifndef FILTER_STAGING_BATCH_PAGES
#define FILTER_STAGING_BATCH_PAGES 32
#endif

#ifndef FILTER_DEFER_READY_ENABLE
#define FILTER_DEFER_READY_ENABLE FILTER_ACCEL_ENABLE
#endif

#ifndef FILTER_DEFER_DRAIN_LOW_WATERMARK
#define FILTER_DEFER_DRAIN_LOW_WATERMARK 0U
#endif

#ifndef FILTER_DEFER_DRAIN_HIGH_WATERMARK
#define FILTER_DEFER_DRAIN_HIGH_WATERMARK 32U
#endif

#ifndef FILTER_DEFER_DRAIN_BUDGET
#define FILTER_DEFER_DRAIN_BUDGET 64U
#endif

#ifndef FILTER_DIRECT_COALESCE_ENABLE
#define FILTER_DIRECT_COALESCE_ENABLE FILTER_ACCEL_ENABLE
#endif

#ifndef FILTER_DIRECT_COALESCE_PAGES
#define FILTER_DIRECT_COALESCE_PAGES 64
#endif

#ifndef FILTER_DIRECT_ASYNC_ENABLE
#define FILTER_DIRECT_ASYNC_ENABLE FILTER_DIRECT_COALESCE_ENABLE
#endif

#ifndef FILTER_DIRECT_ASYNC_TIMEOUT_POLLS_PER_PAGE
#define FILTER_DIRECT_ASYNC_TIMEOUT_POLLS_PER_PAGE 100000U
#endif

/* Disabled in the validated snapshot. Enabling it makes a completed async
 * batch return to the adaptive watermark gate before issuing another batch. */
#ifndef FILTER_DIRECT_ASYNC_RECHECK_WATERMARK_ENABLE
#define FILTER_DIRECT_ASYNC_RECHECK_WATERMARK_ENABLE 0
#endif

#ifndef FILTER_ACCEL_POLL_SERVICE_ENABLE
#define FILTER_ACCEL_POLL_SERVICE_ENABLE FILTER_ACCEL_ENABLE
#endif

#ifndef FILTER_ACCEL_POLL_SERVICE_INTERVAL
#define FILTER_ACCEL_POLL_SERVICE_INTERVAL 64U
#endif

#ifndef FILTER_ACCEL_INPUT_CACHE_OP
#define FILTER_ACCEL_INPUT_CACHE_OP 0
#endif

#if DATA_BUFFER_ENTRIES_PER_DIE < 1 || DATA_BUFFER_ENTRIES_PER_DIE > 128
#error "DATA_BUFFER_ENTRIES_PER_DIE must be in [1, 128]"
#endif

#if REQUEST_ENTRIES_PER_DIE < 1 || REQUEST_ENTRIES_PER_DIE > 8191
#error "REQUEST_ENTRIES_PER_DIE must be in [1, 8191]"
#endif

#if FILTER_MAX_BLOCK_COUNT < 1U || FILTER_MAX_BLOCK_COUNT > 65535U
#error "FILTER_MAX_BLOCK_COUNT must be in [1, 65535]"
#endif

#if FILTER_RESULT_MAX_PAGES < 1 || FILTER_RESULT_MAX_PAGES > 32
#error "FILTER_RESULT_MAX_PAGES must be in [1, 32]"
#endif

#if (FILTER_PROJECTION_ENABLE != 0) && (FILTER_PROJECTION_ENABLE != 1)
#error "FILTER_PROJECTION_ENABLE must be 0 or 1"
#endif

#if (FILTER_COMPUTE_ENABLE != 0) && (FILTER_COMPUTE_ENABLE != 1)
#error "FILTER_COMPUTE_ENABLE must be 0 or 1"
#endif

#if (FILTER_HASH_JOIN_ENABLE != 0) && (FILTER_HASH_JOIN_ENABLE != 1)
#error "FILTER_HASH_JOIN_ENABLE must be 0 or 1"
#endif

#if FILTER_COMPUTE_MAX_SORT_ROWS < 1U
#error "FILTER_COMPUTE_MAX_SORT_ROWS must be >= 1"
#endif

#if FILTER_COMPUTE_MAX_TUPLE_BYTES < 23U || FILTER_COMPUTE_MAX_TUPLE_BYTES > 8192U
#error "FILTER_COMPUTE_MAX_TUPLE_BYTES must be in [23, 8192]"
#endif

#if FILTER_COMPUTE_WORK_BYTES < 4096U || (FILTER_COMPUTE_WORK_BYTES & 63U) != 0U
#error "FILTER_COMPUTE_WORK_BYTES must be at least 4096 and cache-line aligned"
#endif

#if FILTER_JOIN_MIN_BUCKETS < 2U || \
    (FILTER_JOIN_MIN_BUCKETS & (FILTER_JOIN_MIN_BUCKETS - 1U)) != 0U
#error "FILTER_JOIN_MIN_BUCKETS must be a power of two"
#endif

#if FILTER_JOIN_MAX_BUCKETS < FILTER_JOIN_MIN_BUCKETS || \
    (FILTER_JOIN_MAX_BUCKETS & (FILTER_JOIN_MAX_BUCKETS - 1U)) != 0U
#error "FILTER_JOIN_MAX_BUCKETS must be a power of two"
#endif

#if FILTER_JOIN_MAX_BUILD_ROWS < 1U || FILTER_JOIN_MAX_OUTPUT_ROWS < 1U
#error "FILTER_JOIN row limits must be >= 1"
#endif

#if FILTER_JOIN_WORK_BYTES < 4096U || (FILTER_JOIN_WORK_BYTES & 63U) != 0U
#error "FILTER_JOIN_WORK_BYTES must be at least 4096 and cache-line aligned"
#endif

#if FILTER_PROJECTION_STAGING_BYTES_PER_PAGE < 256U || \
    (FILTER_PROJECTION_STAGING_BYTES_PER_PAGE & 3U) != 0U
#error "FILTER_PROJECTION_STAGING_BYTES_PER_PAGE must be >= 256 and 4-byte aligned"
#endif

#if FILTER_PROJECTION_DEFAULT_MAX_ROW_BYTES < 16U || \
    FILTER_PROJECTION_DEFAULT_MAX_ROW_BYTES > FILTER_PROJECTION_STAGING_BYTES_PER_PAGE
#error "FILTER_PROJECTION_DEFAULT_MAX_ROW_BYTES is outside the staging slot"
#endif

#if FILTER_STAGING_BATCH_PAGES < 1 || FILTER_STAGING_BATCH_PAGES > FILTER_ACCEL_MAX_BATCH_PAGES
#error "FILTER_STAGING_BATCH_PAGES exceeds the accelerator batch ABI"
#endif

#if FILTER_DIRECT_COALESCE_PAGES < 1 || FILTER_DIRECT_COALESCE_PAGES > FILTER_ACCEL_MAX_BATCH_PAGES
#error "FILTER_DIRECT_COALESCE_PAGES exceeds the accelerator batch ABI"
#endif

#if FILTER_DEFER_DRAIN_LOW_WATERMARK > 65535U
#error "FILTER_DEFER_DRAIN_LOW_WATERMARK must be in [0, 65535]"
#endif

#if FILTER_DEFER_DRAIN_HIGH_WATERMARK < 1 || FILTER_DEFER_DRAIN_HIGH_WATERMARK > 65535U
#error "FILTER_DEFER_DRAIN_HIGH_WATERMARK must be in [1, 65535]"
#endif

#if FILTER_DEFER_DRAIN_BUDGET < 1 || FILTER_DEFER_DRAIN_BUDGET > 65535U
#error "FILTER_DEFER_DRAIN_BUDGET must be in [1, 65535]"
#endif

#if FILTER_ACCEL_POLL_SERVICE_INTERVAL < 1
#error "FILTER_ACCEL_POLL_SERVICE_INTERVAL must be >= 1"
#endif

#if FILTER_DIRECT_ASYNC_TIMEOUT_POLLS_PER_PAGE < 1
#error "FILTER_DIRECT_ASYNC_TIMEOUT_POLLS_PER_PAGE must be >= 1"
#endif

#if FILTER_ACCEL_INPUT_CACHE_OP < 0 || FILTER_ACCEL_INPUT_CACHE_OP > 2
#error "FILTER_ACCEL_INPUT_CACHE_OP must be 0, 1, or 2"
#endif

#if (FILTER_ACCEL_ENABLE != 0) && (FILTER_ACCEL_ENABLE != 1)
#error "FILTER_ACCEL_ENABLE must be 0 or 1"
#endif

#if (FILTER_ACCEL_VERIFY_ENABLE != 0) && (FILTER_ACCEL_VERIFY_ENABLE != 1)
#error "FILTER_ACCEL_VERIFY_ENABLE must be 0 or 1"
#endif

#if (FILTER_FORCE_ARM_FALLBACK != 0) && (FILTER_FORCE_ARM_FALLBACK != 1)
#error "FILTER_FORCE_ARM_FALLBACK must be 0 or 1"
#endif

#if (FILTER_STAGING_BATCH_ENABLE != 0) && (FILTER_STAGING_BATCH_ENABLE != 1)
#error "FILTER_STAGING_BATCH_ENABLE must be 0 or 1"
#endif

#if (FILTER_DEFER_READY_ENABLE != 0) && (FILTER_DEFER_READY_ENABLE != 1)
#error "FILTER_DEFER_READY_ENABLE must be 0 or 1"
#endif

#if (FILTER_DIRECT_COALESCE_ENABLE != 0) && (FILTER_DIRECT_COALESCE_ENABLE != 1)
#error "FILTER_DIRECT_COALESCE_ENABLE must be 0 or 1"
#endif

#if (FILTER_DIRECT_ASYNC_ENABLE != 0) && (FILTER_DIRECT_ASYNC_ENABLE != 1)
#error "FILTER_DIRECT_ASYNC_ENABLE must be 0 or 1"
#endif

#if (FILTER_DIRECT_ASYNC_RECHECK_WATERMARK_ENABLE != 0) && \
    (FILTER_DIRECT_ASYNC_RECHECK_WATERMARK_ENABLE != 1)
#error "FILTER_DIRECT_ASYNC_RECHECK_WATERMARK_ENABLE must be 0 or 1"
#endif

#if (FILTER_ACCEL_POLL_SERVICE_ENABLE != 0) && (FILTER_ACCEL_POLL_SERVICE_ENABLE != 1)
#error "FILTER_ACCEL_POLL_SERVICE_ENABLE must be 0 or 1"
#endif

#if FILTER_DIRECT_COALESCE_ENABLE && !FILTER_DEFER_READY_ENABLE
#error "FILTER_DIRECT_COALESCE_ENABLE requires FILTER_DEFER_READY_ENABLE"
#endif

#if FILTER_DIRECT_COALESCE_ENABLE && !FILTER_ACCEL_ENABLE
#error "FILTER_DIRECT_COALESCE_ENABLE requires FILTER_ACCEL_ENABLE"
#endif

#if FILTER_DIRECT_ASYNC_ENABLE && !FILTER_DIRECT_COALESCE_ENABLE
#error "FILTER_DIRECT_ASYNC_ENABLE requires FILTER_DIRECT_COALESCE_ENABLE"
#endif

#if FILTER_DIRECT_ASYNC_RECHECK_WATERMARK_ENABLE && !FILTER_DIRECT_ASYNC_ENABLE
#error "FILTER_DIRECT_ASYNC_RECHECK_WATERMARK_ENABLE requires FILTER_DIRECT_ASYNC_ENABLE"
#endif

#if FILTER_STAGING_BATCH_ENABLE && !FILTER_ACCEL_ENABLE
#error "FILTER_STAGING_BATCH_ENABLE requires FILTER_ACCEL_ENABLE"
#endif

#if FILTER_ACCEL_VERIFY_ENABLE && !FILTER_ACCEL_ENABLE
#error "FILTER_ACCEL_VERIFY_ENABLE requires FILTER_ACCEL_ENABLE"
#endif

#if FILTER_ACCEL_POLL_SERVICE_ENABLE && !FILTER_ACCEL_ENABLE
#error "FILTER_ACCEL_POLL_SERVICE_ENABLE requires FILTER_ACCEL_ENABLE"
#endif

#endif /* FILTER_CONFIG_H_ */
