-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (win64) Build 6140274 Thu May 22 00:12:29 MDT 2025
-- Date        : Tue Jul  8 14:21:11 2025
-- Host        : DESKTOP-JP2R5GF running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub -rename_top sys_top_t4nfc_hlper_1_0 -prefix
--               sys_top_t4nfc_hlper_1_0_ sys_top_t4nfc_hlper_0_0_stub.vhdl
-- Design      : sys_top_t4nfc_hlper_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu17eg-ffvc1760-2-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity sys_top_t4nfc_hlper_1_0 is
  Port ( 
    iClock : in STD_LOGIC;
    iReset : in STD_LOGIC;
    C_AWVALID : in STD_LOGIC;
    C_AWREADY : out STD_LOGIC;
    C_AWADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    C_AWPROT : in STD_LOGIC_VECTOR ( 2 downto 0 );
    C_WVALID : in STD_LOGIC;
    C_WREADY : out STD_LOGIC;
    C_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    C_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    C_BVALID : out STD_LOGIC;
    C_BREADY : in STD_LOGIC;
    C_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    C_ARVALID : in STD_LOGIC;
    C_ARREADY : out STD_LOGIC;
    C_ARADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    C_ARPROT : in STD_LOGIC_VECTOR ( 2 downto 0 );
    C_RVALID : out STD_LOGIC;
    C_RREADY : in STD_LOGIC;
    C_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    C_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    D_AWADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    D_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    D_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    D_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_AWVALID : out STD_LOGIC;
    D_AWREADY : in STD_LOGIC;
    D_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    D_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_WLAST : out STD_LOGIC;
    D_WVALID : out STD_LOGIC;
    D_WREADY : in STD_LOGIC;
    D_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    D_BVALID : in STD_LOGIC;
    D_BREADY : out STD_LOGIC;
    D_ARADDR : out STD_LOGIC_VECTOR ( 31 downto 0 );
    D_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    D_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    D_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    D_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    D_ARVALID : out STD_LOGIC;
    D_ARREADY : in STD_LOGIC;
    D_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    D_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    D_RLAST : in STD_LOGIC;
    D_RVALID : in STD_LOGIC;
    D_RREADY : out STD_LOGIC;
    oOpcode : out STD_LOGIC_VECTOR ( 5 downto 0 );
    oTargetID : out STD_LOGIC_VECTOR ( 4 downto 0 );
    oSourceID : out STD_LOGIC_VECTOR ( 4 downto 0 );
    oAddress : out STD_LOGIC_VECTOR ( 31 downto 0 );
    oLength : out STD_LOGIC_VECTOR ( 15 downto 0 );
    oCMDValid : out STD_LOGIC;
    iCMDReady : in STD_LOGIC;
    oWriteData : out STD_LOGIC_VECTOR ( 31 downto 0 );
    oWriteLast : out STD_LOGIC;
    oWriteValid : out STD_LOGIC;
    iWriteReady : in STD_LOGIC;
    iReadData : in STD_LOGIC_VECTOR ( 31 downto 0 );
    iReadLast : in STD_LOGIC;
    iReadValid : in STD_LOGIC;
    oReadReady : out STD_LOGIC;
    iReadyBusy : in STD_LOGIC_VECTOR ( 7 downto 0 );
    oROMClock : out STD_LOGIC;
    oROMReset : out STD_LOGIC;
    oROMAddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    oROMRW : out STD_LOGIC;
    oROMEnable : out STD_LOGIC;
    oROMWData : out STD_LOGIC_VECTOR ( 31 downto 0 );
    iROMRData : in STD_LOGIC_VECTOR ( 31 downto 0 );
    oToECCWOpcode : out STD_LOGIC_VECTOR ( 5 downto 0 );
    oToECCWTargetID : out STD_LOGIC_VECTOR ( 4 downto 0 );
    oToECCWSourceID : out STD_LOGIC_VECTOR ( 4 downto 0 );
    oToECCWAddress : out STD_LOGIC_VECTOR ( 31 downto 0 );
    oToECCWLength : out STD_LOGIC_VECTOR ( 15 downto 0 );
    oToECCWCmdValid : out STD_LOGIC;
    iToECCWCmdReady : in STD_LOGIC;
    oToECCWData : out STD_LOGIC_VECTOR ( 31 downto 0 );
    oToECCWValid : out STD_LOGIC;
    oToECCWLast : out STD_LOGIC;
    iToECCWReady : in STD_LOGIC;
    oToECCROpcode : out STD_LOGIC_VECTOR ( 5 downto 0 );
    oToECCRTargetID : out STD_LOGIC_VECTOR ( 4 downto 0 );
    oToECCRSourceID : out STD_LOGIC_VECTOR ( 4 downto 0 );
    oToECCRAddress : out STD_LOGIC_VECTOR ( 31 downto 0 );
    oToECCRLength : out STD_LOGIC_VECTOR ( 15 downto 0 );
    oToECCRCmdValid : out STD_LOGIC;
    iToECCRCmdReady : in STD_LOGIC;
    iToECCRData : in STD_LOGIC_VECTOR ( 31 downto 0 );
    iToECCRValid : in STD_LOGIC;
    iToECCRLast : in STD_LOGIC;
    oToECCRReady : out STD_LOGIC;
    ifromECCWOpcode : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ifromECCWTargetID : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ifromECCWSourceID : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ifromECCWAddress : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ifromECCWLength : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ifromECCWCmdValid : in STD_LOGIC;
    ofromECCWCmdReady : out STD_LOGIC;
    ifromECCWData : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ifromECCWValid : in STD_LOGIC;
    ifromECCWLast : in STD_LOGIC;
    ofromECCWReady : out STD_LOGIC;
    ifromECCROpcode : in STD_LOGIC_VECTOR ( 5 downto 0 );
    ifromECCRTargetID : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ifromECCRSourceID : in STD_LOGIC_VECTOR ( 4 downto 0 );
    ifromECCRAddress : in STD_LOGIC_VECTOR ( 31 downto 0 );
    ifromECCRLength : in STD_LOGIC_VECTOR ( 15 downto 0 );
    ifromECCRCmdValid : in STD_LOGIC;
    ofromECCRCmdReady : out STD_LOGIC;
    ofromECCRData : out STD_LOGIC_VECTOR ( 31 downto 0 );
    ofromECCRValid : out STD_LOGIC;
    ofromECCRLast : out STD_LOGIC;
    ifromECCRReady : in STD_LOGIC;
    O_DEBUG : out STD_LOGIC_VECTOR ( 31 downto 0 )
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of sys_top_t4nfc_hlper_1_0 : entity is "sys_top_t4nfc_hlper_0_0,FMCTop,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of sys_top_t4nfc_hlper_1_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of sys_top_t4nfc_hlper_1_0 : entity is "package_project";
end sys_top_t4nfc_hlper_1_0;

architecture stub of sys_top_t4nfc_hlper_1_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "iClock,iReset,C_AWVALID,C_AWREADY,C_AWADDR[31:0],C_AWPROT[2:0],C_WVALID,C_WREADY,C_WDATA[31:0],C_WSTRB[3:0],C_BVALID,C_BREADY,C_BRESP[1:0],C_ARVALID,C_ARREADY,C_ARADDR[31:0],C_ARPROT[2:0],C_RVALID,C_RREADY,C_RDATA[31:0],C_RRESP[1:0],D_AWADDR[31:0],D_AWLEN[7:0],D_AWSIZE[2:0],D_AWBURST[1:0],D_AWCACHE[3:0],D_AWPROT[2:0],D_AWVALID,D_AWREADY,D_WDATA[31:0],D_WSTRB[3:0],D_WLAST,D_WVALID,D_WREADY,D_BRESP[1:0],D_BVALID,D_BREADY,D_ARADDR[31:0],D_ARLEN[7:0],D_ARSIZE[2:0],D_ARBURST[1:0],D_ARCACHE[3:0],D_ARPROT[2:0],D_ARVALID,D_ARREADY,D_RDATA[31:0],D_RRESP[1:0],D_RLAST,D_RVALID,D_RREADY,oOpcode[5:0],oTargetID[4:0],oSourceID[4:0],oAddress[31:0],oLength[15:0],oCMDValid,iCMDReady,oWriteData[31:0],oWriteLast,oWriteValid,iWriteReady,iReadData[31:0],iReadLast,iReadValid,oReadReady,iReadyBusy[7:0],oROMClock,oROMReset,oROMAddr[31:0],oROMRW,oROMEnable,oROMWData[31:0],iROMRData[31:0],oToECCWOpcode[5:0],oToECCWTargetID[4:0],oToECCWSourceID[4:0],oToECCWAddress[31:0],oToECCWLength[15:0],oToECCWCmdValid,iToECCWCmdReady,oToECCWData[31:0],oToECCWValid,oToECCWLast,iToECCWReady,oToECCROpcode[5:0],oToECCRTargetID[4:0],oToECCRSourceID[4:0],oToECCRAddress[31:0],oToECCRLength[15:0],oToECCRCmdValid,iToECCRCmdReady,iToECCRData[31:0],iToECCRValid,iToECCRLast,oToECCRReady,ifromECCWOpcode[5:0],ifromECCWTargetID[4:0],ifromECCWSourceID[4:0],ifromECCWAddress[31:0],ifromECCWLength[15:0],ifromECCWCmdValid,ofromECCWCmdReady,ifromECCWData[31:0],ifromECCWValid,ifromECCWLast,ofromECCWReady,ifromECCROpcode[5:0],ifromECCRTargetID[4:0],ifromECCRSourceID[4:0],ifromECCRAddress[31:0],ifromECCRLength[15:0],ifromECCRCmdValid,ofromECCRCmdReady,ofromECCRData[31:0],ofromECCRValid,ofromECCRLast,ifromECCRReady,O_DEBUG[31:0]";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of iClock : signal is "xilinx.com:signal:clock:1.0 iClock CLK";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of iClock : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of iClock : signal is "XIL_INTERFACENAME iClock, ASSOCIATED_BUSIF nfch_cmd_if:nfch_data_if:v2nfc_if:to_ecc_if:from_ecc_if, ASSOCIATED_RESET iReset, FREQ_HZ 66666000, PHASE 0.0, CLK_DOMAIN /pll_bank10_clk_out1, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of iReset : signal is "xilinx.com:signal:reset:1.0 iReset RST";
  attribute X_INTERFACE_MODE of iReset : signal is "slave";
  attribute X_INTERFACE_PARAMETER of iReset : signal is "XIL_INTERFACENAME iReset, POLARITY ACTIVE_HIGH, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of C_AWVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if AWVALID";
  attribute X_INTERFACE_MODE of C_AWVALID : signal is "slave";
  attribute X_INTERFACE_PARAMETER of C_AWVALID : signal is "XIL_INTERFACENAME nfch_cmd_if, DATA_WIDTH 32, PROTOCOL AXI4LITE, FREQ_HZ 66666000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN /pll_bank10_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of C_AWREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if AWREADY";
  attribute X_INTERFACE_INFO of C_AWADDR : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if AWADDR";
  attribute X_INTERFACE_INFO of C_AWPROT : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if AWPROT";
  attribute X_INTERFACE_INFO of C_WVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if WVALID";
  attribute X_INTERFACE_INFO of C_WREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if WREADY";
  attribute X_INTERFACE_INFO of C_WDATA : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if WDATA";
  attribute X_INTERFACE_INFO of C_WSTRB : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if WSTRB";
  attribute X_INTERFACE_INFO of C_BVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if BVALID";
  attribute X_INTERFACE_INFO of C_BREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if BREADY";
  attribute X_INTERFACE_INFO of C_BRESP : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if BRESP";
  attribute X_INTERFACE_INFO of C_ARVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if ARVALID";
  attribute X_INTERFACE_INFO of C_ARREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if ARREADY";
  attribute X_INTERFACE_INFO of C_ARADDR : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if ARADDR";
  attribute X_INTERFACE_INFO of C_ARPROT : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if ARPROT";
  attribute X_INTERFACE_INFO of C_RVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if RVALID";
  attribute X_INTERFACE_INFO of C_RREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if RREADY";
  attribute X_INTERFACE_INFO of C_RDATA : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if RDATA";
  attribute X_INTERFACE_INFO of C_RRESP : signal is "xilinx.com:interface:aximm:1.0 nfch_cmd_if RRESP";
  attribute X_INTERFACE_INFO of D_AWADDR : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWADDR";
  attribute X_INTERFACE_MODE of D_AWADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of D_AWADDR : signal is "XIL_INTERFACENAME nfch_data_if, DATA_WIDTH 32, PROTOCOL AXI4, FREQ_HZ 66666000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 256, PHASE 0.0, CLK_DOMAIN /pll_bank10_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of D_AWLEN : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWLEN";
  attribute X_INTERFACE_INFO of D_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWSIZE";
  attribute X_INTERFACE_INFO of D_AWBURST : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWBURST";
  attribute X_INTERFACE_INFO of D_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWCACHE";
  attribute X_INTERFACE_INFO of D_AWPROT : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWPROT";
  attribute X_INTERFACE_INFO of D_AWVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWVALID";
  attribute X_INTERFACE_INFO of D_AWREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if AWREADY";
  attribute X_INTERFACE_INFO of D_WDATA : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if WDATA";
  attribute X_INTERFACE_INFO of D_WSTRB : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if WSTRB";
  attribute X_INTERFACE_INFO of D_WLAST : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if WLAST";
  attribute X_INTERFACE_INFO of D_WVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if WVALID";
  attribute X_INTERFACE_INFO of D_WREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if WREADY";
  attribute X_INTERFACE_INFO of D_BRESP : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if BRESP";
  attribute X_INTERFACE_INFO of D_BVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if BVALID";
  attribute X_INTERFACE_INFO of D_BREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if BREADY";
  attribute X_INTERFACE_INFO of D_ARADDR : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARADDR";
  attribute X_INTERFACE_INFO of D_ARLEN : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARLEN";
  attribute X_INTERFACE_INFO of D_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARSIZE";
  attribute X_INTERFACE_INFO of D_ARBURST : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARBURST";
  attribute X_INTERFACE_INFO of D_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARCACHE";
  attribute X_INTERFACE_INFO of D_ARPROT : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARPROT";
  attribute X_INTERFACE_INFO of D_ARVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARVALID";
  attribute X_INTERFACE_INFO of D_ARREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if ARREADY";
  attribute X_INTERFACE_INFO of D_RDATA : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if RDATA";
  attribute X_INTERFACE_INFO of D_RRESP : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if RRESP";
  attribute X_INTERFACE_INFO of D_RLAST : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if RLAST";
  attribute X_INTERFACE_INFO of D_RVALID : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if RVALID";
  attribute X_INTERFACE_INFO of D_RREADY : signal is "xilinx.com:interface:aximm:1.0 nfch_data_if RREADY";
  attribute X_INTERFACE_INFO of oOpcode : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if Opcode";
  attribute X_INTERFACE_MODE of oOpcode : signal is "master";
  attribute X_INTERFACE_INFO of oTargetID : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if TargetID";
  attribute X_INTERFACE_INFO of oSourceID : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if SourceID";
  attribute X_INTERFACE_INFO of oAddress : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if Address";
  attribute X_INTERFACE_INFO of oLength : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if Length";
  attribute X_INTERFACE_INFO of oCMDValid : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if CMDValid";
  attribute X_INTERFACE_INFO of iCMDReady : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if CMDReady";
  attribute X_INTERFACE_INFO of oWriteData : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if WriteData";
  attribute X_INTERFACE_INFO of oWriteLast : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if WriteLast";
  attribute X_INTERFACE_INFO of oWriteValid : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if WriteValid";
  attribute X_INTERFACE_INFO of iWriteReady : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if WriteReady";
  attribute X_INTERFACE_INFO of iReadData : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if ReadData";
  attribute X_INTERFACE_INFO of iReadLast : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if ReadLast";
  attribute X_INTERFACE_INFO of iReadValid : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if ReadValid";
  attribute X_INTERFACE_INFO of oReadReady : signal is "enclab:user:v2nfc_if:1.0 v2nfc_if ReadReady";
  attribute X_INTERFACE_INFO of oROMClock : signal is "xilinx.com:interface:bram:1.0 ucode_if CLK";
  attribute X_INTERFACE_MODE of oROMClock : signal is "master";
  attribute X_INTERFACE_PARAMETER of oROMClock : signal is "XIL_INTERFACENAME ucode_if, MEM_SIZE 8192, MEM_WIDTH 32, MEM_ECC NONE, MASTER_TYPE OTHER, READ_LATENCY 1";
  attribute X_INTERFACE_INFO of oROMReset : signal is "xilinx.com:interface:bram:1.0 ucode_if RST";
  attribute X_INTERFACE_INFO of oROMAddr : signal is "xilinx.com:interface:bram:1.0 ucode_if ADDR";
  attribute X_INTERFACE_INFO of oROMRW : signal is "xilinx.com:interface:bram:1.0 ucode_if WE";
  attribute X_INTERFACE_INFO of oROMEnable : signal is "xilinx.com:interface:bram:1.0 ucode_if EN";
  attribute X_INTERFACE_INFO of oROMWData : signal is "xilinx.com:interface:bram:1.0 ucode_if DIN";
  attribute X_INTERFACE_INFO of iROMRData : signal is "xilinx.com:interface:bram:1.0 ucode_if DOUT";
  attribute X_INTERFACE_INFO of oToECCWOpcode : signal is "enclab:user:ecc_if:1.0 to_ecc_if WOpcode";
  attribute X_INTERFACE_MODE of oToECCWOpcode : signal is "master";
  attribute X_INTERFACE_INFO of oToECCWTargetID : signal is "enclab:user:ecc_if:1.0 to_ecc_if WTargetID";
  attribute X_INTERFACE_INFO of oToECCWSourceID : signal is "enclab:user:ecc_if:1.0 to_ecc_if WSourceID";
  attribute X_INTERFACE_INFO of oToECCWAddress : signal is "enclab:user:ecc_if:1.0 to_ecc_if WAddress";
  attribute X_INTERFACE_INFO of oToECCWLength : signal is "enclab:user:ecc_if:1.0 to_ecc_if WLength";
  attribute X_INTERFACE_INFO of oToECCWCmdValid : signal is "enclab:user:ecc_if:1.0 to_ecc_if WCmdValid";
  attribute X_INTERFACE_INFO of iToECCWCmdReady : signal is "enclab:user:ecc_if:1.0 to_ecc_if WCmdReady";
  attribute X_INTERFACE_INFO of oToECCWData : signal is "enclab:user:ecc_if:1.0 to_ecc_if WData";
  attribute X_INTERFACE_INFO of oToECCWValid : signal is "enclab:user:ecc_if:1.0 to_ecc_if WValid";
  attribute X_INTERFACE_INFO of oToECCWLast : signal is "enclab:user:ecc_if:1.0 to_ecc_if WLast";
  attribute X_INTERFACE_INFO of iToECCWReady : signal is "enclab:user:ecc_if:1.0 to_ecc_if WReady";
  attribute X_INTERFACE_INFO of oToECCROpcode : signal is "enclab:user:ecc_if:1.0 to_ecc_if ROpcode";
  attribute X_INTERFACE_INFO of oToECCRTargetID : signal is "enclab:user:ecc_if:1.0 to_ecc_if RTargetID";
  attribute X_INTERFACE_INFO of oToECCRSourceID : signal is "enclab:user:ecc_if:1.0 to_ecc_if RSourceID";
  attribute X_INTERFACE_INFO of oToECCRAddress : signal is "enclab:user:ecc_if:1.0 to_ecc_if RAddress";
  attribute X_INTERFACE_INFO of oToECCRLength : signal is "enclab:user:ecc_if:1.0 to_ecc_if RLength";
  attribute X_INTERFACE_INFO of oToECCRCmdValid : signal is "enclab:user:ecc_if:1.0 to_ecc_if RCmdValid";
  attribute X_INTERFACE_INFO of iToECCRCmdReady : signal is "enclab:user:ecc_if:1.0 to_ecc_if RCmdReady";
  attribute X_INTERFACE_INFO of iToECCRData : signal is "enclab:user:ecc_if:1.0 to_ecc_if RData";
  attribute X_INTERFACE_INFO of iToECCRValid : signal is "enclab:user:ecc_if:1.0 to_ecc_if RValid";
  attribute X_INTERFACE_INFO of iToECCRLast : signal is "enclab:user:ecc_if:1.0 to_ecc_if RLast";
  attribute X_INTERFACE_INFO of oToECCRReady : signal is "enclab:user:ecc_if:1.0 to_ecc_if RReady";
  attribute X_INTERFACE_INFO of ifromECCWOpcode : signal is "enclab:user:ecc_if:1.0 from_ecc_if WOpcode";
  attribute X_INTERFACE_MODE of ifromECCWOpcode : signal is "slave";
  attribute X_INTERFACE_INFO of ifromECCWTargetID : signal is "enclab:user:ecc_if:1.0 from_ecc_if WTargetID";
  attribute X_INTERFACE_INFO of ifromECCWSourceID : signal is "enclab:user:ecc_if:1.0 from_ecc_if WSourceID";
  attribute X_INTERFACE_INFO of ifromECCWAddress : signal is "enclab:user:ecc_if:1.0 from_ecc_if WAddress";
  attribute X_INTERFACE_INFO of ifromECCWLength : signal is "enclab:user:ecc_if:1.0 from_ecc_if WLength";
  attribute X_INTERFACE_INFO of ifromECCWCmdValid : signal is "enclab:user:ecc_if:1.0 from_ecc_if WCmdValid";
  attribute X_INTERFACE_INFO of ofromECCWCmdReady : signal is "enclab:user:ecc_if:1.0 from_ecc_if WCmdReady";
  attribute X_INTERFACE_INFO of ifromECCWData : signal is "enclab:user:ecc_if:1.0 from_ecc_if WData";
  attribute X_INTERFACE_INFO of ifromECCWValid : signal is "enclab:user:ecc_if:1.0 from_ecc_if WValid";
  attribute X_INTERFACE_INFO of ifromECCWLast : signal is "enclab:user:ecc_if:1.0 from_ecc_if WLast";
  attribute X_INTERFACE_INFO of ofromECCWReady : signal is "enclab:user:ecc_if:1.0 from_ecc_if WReady";
  attribute X_INTERFACE_INFO of ifromECCROpcode : signal is "enclab:user:ecc_if:1.0 from_ecc_if ROpcode";
  attribute X_INTERFACE_INFO of ifromECCRTargetID : signal is "enclab:user:ecc_if:1.0 from_ecc_if RTargetID";
  attribute X_INTERFACE_INFO of ifromECCRSourceID : signal is "enclab:user:ecc_if:1.0 from_ecc_if RSourceID";
  attribute X_INTERFACE_INFO of ifromECCRAddress : signal is "enclab:user:ecc_if:1.0 from_ecc_if RAddress";
  attribute X_INTERFACE_INFO of ifromECCRLength : signal is "enclab:user:ecc_if:1.0 from_ecc_if RLength";
  attribute X_INTERFACE_INFO of ifromECCRCmdValid : signal is "enclab:user:ecc_if:1.0 from_ecc_if RCmdValid";
  attribute X_INTERFACE_INFO of ofromECCRCmdReady : signal is "enclab:user:ecc_if:1.0 from_ecc_if RCmdReady";
  attribute X_INTERFACE_INFO of ofromECCRData : signal is "enclab:user:ecc_if:1.0 from_ecc_if RData";
  attribute X_INTERFACE_INFO of ofromECCRValid : signal is "enclab:user:ecc_if:1.0 from_ecc_if RValid";
  attribute X_INTERFACE_INFO of ofromECCRLast : signal is "enclab:user:ecc_if:1.0 from_ecc_if RLast";
  attribute X_INTERFACE_INFO of ifromECCRReady : signal is "enclab:user:ecc_if:1.0 from_ecc_if RReady";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "FMCTop,Vivado 2025.1";
begin
end;
